{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Library Management",
    "description" : "The API for a library management project",
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "https://virtserver.swaggerhub.com/HEIFEDORA3/LibraryManagement/1.0.0",
    "description" : "SwaggerHub API Auto Mocking"
  } ],
  "components" : { }
}